[tools]
bun = "latest"
deno = "latest"
"go:github.com/dlvhdr/diffnav" = "latest"
elixir = "latest"
erlang = "latest"
hyperfine = "latest"
ghcup = "latest"
go = "latest"
gum = "latest"
jj = "latest"
node = "latest"
"cargo:https://github.com/nushell/nufmt" = "latest"
"go:github.com/opencode-ai/opencode" = "latest"
"aqua:pnpm" = "latest"
rust = "latest"
task = "latest"
typos = "latest"
"npm:@getgrit/cli" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@withgraphite/graphite-cli" = "latest"
yq = "latest"

[settings]
disable_backends = ["asdf"]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]

[settings.npm]
bun = true
