# TUIOS Configuration File
# This file allows you to customize keybindings
# Edit keybindings by modifying the arrays of keys for each action
# Multiple keys can be bound to the same action
#
# Configuration location: /Users/cfb/.config/tuios/config.toml
# Documentation: https://github.com/Gaurav-Gosain/tuios

[keybindings]
[keybindings.window_management]
close_window = ['w', 'x']
minimize_window = ['m']
new_window = ['n']
next_window = ['tab']
prev_window = ['shift+tab']
rename_window = ['r']
restore_all = ['M']
select_window_1 = ['1']
select_window_2 = ['2']
select_window_3 = ['3']
select_window_4 = ['4']
select_window_5 = ['5']
select_window_6 = ['6']
select_window_7 = ['7']
select_window_8 = ['8']
select_window_9 = ['9']

[keybindings.workspaces]
move_and_follow_1 = ['opt+shift+1']
move_and_follow_2 = ['opt+shift+2']
move_and_follow_3 = ['opt+shift+3']
move_and_follow_4 = ['opt+shift+4']
move_and_follow_5 = ['opt+shift+5']
move_and_follow_6 = ['opt+shift+6']
move_and_follow_7 = ['opt+shift+7']
move_and_follow_8 = ['opt+shift+8']
move_and_follow_9 = ['opt+shift+9']
switch_workspace_1 = ['opt+1']
switch_workspace_2 = ['opt+2']
switch_workspace_3 = ['opt+3']
switch_workspace_4 = ['opt+4']
switch_workspace_5 = ['opt+5']
switch_workspace_6 = ['opt+6']
switch_workspace_7 = ['opt+7']
switch_workspace_8 = ['opt+8']
switch_workspace_9 = ['opt+9']

[keybindings.layout]
snap_corner_1 = ['1']
snap_corner_2 = ['2']
snap_corner_3 = ['3']
snap_corner_4 = ['4']
snap_fullscreen = ['f']
snap_left = ['h']
snap_right = ['l']
swap_down = ['J', 'ctrl+down']
swap_left = ['H', 'ctrl+left']
swap_right = ['L', 'ctrl+right']
swap_up = ['K', 'ctrl+up']
toggle_tiling = ['t']
unsnap = ['u']

[keybindings.mode_control]
enter_terminal_mode = ['i', 'enter']
enter_window_mode = ['esc']
quit = ['q']
toggle_help = ['?']

[keybindings.system]

[keybindings.navigation]
extend_down = ['shift+down']
extend_left = ['shift+left']
extend_right = ['shift+right']
extend_up = ['shift+up']
nav_down = ['down']
nav_left = ['left']
nav_right = ['right']
nav_up = ['up']

[keybindings.restore_minimized]
restore_minimized_1 = ['shift+1', '!']
restore_minimized_2 = ['shift+2', '@']
restore_minimized_3 = ['shift+3', '#']
restore_minimized_4 = ['shift+4', '$']
restore_minimized_5 = ['shift+5', '%']
restore_minimized_6 = ['shift+6', '^']
restore_minimized_7 = ['shift+7', '&']
restore_minimized_8 = ['shift+8', '*']
restore_minimized_9 = ['shift+9', '(']

[keybindings.prefix_mode]
prefix_close_window = ['x']
prefix_debug = ['D']
prefix_detach = ['d', 'esc']
prefix_fullscreen = ['z']
prefix_help = ['?']
prefix_minimize = ['m']
prefix_new_window = ['c']
prefix_next_window = ['n', 'tab']
prefix_prev_window = ['p', 'shift+tab']
prefix_quit = ['q']
prefix_rename_window = [',', 'r']
prefix_select_0 = ['0']
prefix_select_1 = ['1']
prefix_select_2 = ['2']
prefix_select_3 = ['3']
prefix_select_4 = ['4']
prefix_select_5 = ['5']
prefix_select_6 = ['6']
prefix_select_7 = ['7']
prefix_select_8 = ['8']
prefix_select_9 = ['9']
prefix_selection = ['[']
prefix_toggle_tiling = ['space']
prefix_window = ['t']
prefix_workspace = ['w']

[keybindings.window_prefix]
window_prefix_cancel = ['esc']
window_prefix_close = ['x']
window_prefix_new = ['n']
window_prefix_next = ['tab']
window_prefix_prev = ['shift+tab']
window_prefix_rename = ['r']
window_prefix_tiling = ['t']

[keybindings.minimize_prefix]
minimize_prefix_cancel = ['esc']
minimize_prefix_focused = ['m']
minimize_prefix_restore_1 = ['1']
minimize_prefix_restore_2 = ['2']
minimize_prefix_restore_3 = ['3']
minimize_prefix_restore_4 = ['4']
minimize_prefix_restore_5 = ['5']
minimize_prefix_restore_6 = ['6']
minimize_prefix_restore_7 = ['7']
minimize_prefix_restore_8 = ['8']
minimize_prefix_restore_9 = ['9']
minimize_prefix_restore_all = ['M']

[keybindings.workspace_prefix]
workspace_prefix_cancel = ['esc']
workspace_prefix_move_1 = ['!']
workspace_prefix_move_2 = ['@']
workspace_prefix_move_3 = ['#']
workspace_prefix_move_4 = ['$']
workspace_prefix_move_5 = ['%']
workspace_prefix_move_6 = ['^']
workspace_prefix_move_7 = ['&']
workspace_prefix_move_8 = ['*']
workspace_prefix_move_9 = ['(']
workspace_prefix_switch_1 = ['1']
workspace_prefix_switch_2 = ['2']
workspace_prefix_switch_3 = ['3']
workspace_prefix_switch_4 = ['4']
workspace_prefix_switch_5 = ['5']
workspace_prefix_switch_6 = ['6']
workspace_prefix_switch_7 = ['7']
workspace_prefix_switch_8 = ['8']
workspace_prefix_switch_9 = ['9']

[keybindings.debug_prefix]
debug_prefix_cache = ['c']
debug_prefix_cancel = ['esc']
debug_prefix_logs = ['l']
